// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn9YrsAJnozm3KDMjZxp_8t9keoDvwEZE',
    appId: '1:125451920153:web:201d35059d2d8d3cbb1b88',
    messagingSenderId: '125451920153',
    projectId: 'abarrotes-c06d5',
    authDomain: 'abarrotes-c06d5.firebaseapp.com',
    storageBucket: 'abarrotes-c06d5.appspot.com',
    measurementId: 'G-NDDV9CLH1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmnfvec4N2s-1rZWwyUCojsiEqfG2SyBk',
    appId: '1:125451920153:android:2d9ed26c21ec25ecbb1b88',
    messagingSenderId: '125451920153',
    projectId: 'abarrotes-c06d5',
    storageBucket: 'abarrotes-c06d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsCTpubW9WxhT_N6lq07DuiqEUZZSUb9Q',
    appId: '1:125451920153:ios:0ce18917e7736a53bb1b88',
    messagingSenderId: '125451920153',
    projectId: 'abarrotes-c06d5',
    storageBucket: 'abarrotes-c06d5.appspot.com',
    iosBundleId: 'com.example.abarrotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsCTpubW9WxhT_N6lq07DuiqEUZZSUb9Q',
    appId: '1:125451920153:ios:0ce18917e7736a53bb1b88',
    messagingSenderId: '125451920153',
    projectId: 'abarrotes-c06d5',
    storageBucket: 'abarrotes-c06d5.appspot.com',
    iosBundleId: 'com.example.abarrotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn9YrsAJnozm3KDMjZxp_8t9keoDvwEZE',
    appId: '1:125451920153:web:0944718811baeee8bb1b88',
    messagingSenderId: '125451920153',
    projectId: 'abarrotes-c06d5',
    authDomain: 'abarrotes-c06d5.firebaseapp.com',
    storageBucket: 'abarrotes-c06d5.appspot.com',
    measurementId: 'G-598R4V5B8B',
  );
}
